import type { Metadata } from 'next';
import { Providers } from './providers';
import 'react-notifications-component/dist/theme.css';
import '@/styles/global.scss';
import 'reactjs-popup/dist/index.css';
import 'animate.css';

import { Provider } from '@/components/ui/provider';
import { Theme } from '@chakra-ui/react';
import Script from 'next/script';
import Head from 'next/head';
import { Toaster } from '@/components/ui/toaster';

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang='en'>
			<head>
				<link
					rel='stylesheet'
					href='https://cdn.direct.i-dgtl.ru/VerifyWidget.css'
				/>
			</head>
			<body>
				<Script src='https://cdn.direct.i-dgtl.ru/VerifyWidget.umd.min.js'></Script>
				<Provider defaultTheme='light'>
					<Theme
						appearance='light'
						colorPalette={'blue'}
					>
						<Toaster />
						<Providers>{children}</Providers>
					</Theme>
				</Provider>
			</body>
		</html>
	);
}
