import type { Metadata } from "next";
import { Providers } from "./providers";
import 'react-notifications-component/dist/theme.css'
import  "@/styles/global.scss";
import 'reactjs-popup/dist/index.css';
import 'animate.css'

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout( {
  children,
}: Readonly<{
  children: React.ReactNode;
}> ) {
  return (

    <html lang="en">

      <body>
        <Providers>
          { children }
        </Providers>
      </body>
    </html>


  );
}
